In [2]:
import cv2
import numpy as np
import matplotlib.pyplot as plt


In [149]:
for i in range(1,10):
    print i
    img= cv2.imread('/home/lein/Dropbox/uw/figures/ice%s.jpg'%i);
    HH=img[:,:,0]
    cv2.imwrite('/home/lein/Dropbox/uw/figures/ice%s.jpg'%i, HH);

1
2
3
4
5
6
7
8
9


In [125]:
print img

[[[41 27 51]
  [40 26 50]
  [38 24 48]
  ..., 
  [47 27 50]
  [42 22 45]
  [41 20 45]]

 [[40 26 50]
  [40 26 50]
  [38 24 48]
  ..., 
  [53 33 56]
  [48 28 51]
  [44 23 48]]

 [[40 26 50]
  [39 25 49]
  [39 25 49]
  ..., 
  [49 29 52]
  [50 30 53]
  [50 29 54]]

 ..., 
 [[41 25 56]
  [40 24 55]
  [39 23 54]
  ..., 
  [42 29 73]
  [41 30 76]
  [43 31 79]]

 [[41 25 56]
  [40 24 55]
  [39 23 54]
  ..., 
  [40 27 71]
  [40 27 71]
  [41 28 74]]

 [[40 24 55]
  [39 23 54]
  [39 23 54]
  ..., 
  [38 25 69]
  [38 25 69]
  [38 25 69]]]


In [143]:

cv2.imwrite('ice.jpg',img)
im2=cv2.imread('ice.jpg');
img==im2
from scipy.misc import imsave

import matplotlib.image
read_img = matplotlib.image.imread('./ICE_WATER/ice2.jpg')
plt.imshow(read_img)

In [144]:
HH=read_img[:,:,0]
HV=read_img[:,:,1]
IC=read_img[:,:,2]
HH.shape

(45, 45)

In [145]:
HH

array([[66, 65, 65, ..., 55, 55, 56],
       [66, 65, 65, ..., 55, 55, 56],
       [66, 65, 65, ..., 59, 61, 61],
       ..., 
       [40, 37, 36, ..., 79, 80, 82],
       [34, 31, 32, ..., 79, 82, 89],
       [34, 31, 32, ..., 79, 83, 95]], dtype=uint8)

In [146]:
imsave('water_hh.tif',HH)
imsave('water_hv.tif',HV)
imsave('water_ic.tif',IC)

/home/lein/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:1: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  """Entry point for launching an IPython kernel.
/home/lein/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:2: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  
/home/lein/miniconda2/lib/python2.7/site-packages/ipykernel_launcher.py:3: DeprecationWarning: `imsave` is deprecated!
`imsave` is deprecated in SciPy 1.0.0, and will be removed in 1.2.0.
Use ``imageio.imwrite`` instead.
  This is separate from the ipykernel package so we can avoid doing imports until


In [147]:
cv2.imread('water_hh.tif').shape

(45, 45, 3)